spring:
  application:
    name: Smash
  main:
    lazy-initialization: false
    banner-mode: "off"
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://${io.github.paulushcgcj.postgres.host}/${io.github.paulushcgcj.postgres.database}
    username: ${io.github.paulushcgcj.postgres.username}
    password: ${io.github.paulushcgcj.postgres.password}
    pool:
      enabled: true
      initialSize: 1
      minIdle: 1
      maxSize: 3
      maxLifeTime: 60000
      maxIdleTime: 45000
      maxCreateConnectionTime: 90000
      poolName: FsaClientConPool
  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    schemas: smash
    default-schema: smash
    user: ${io.github.paulushcgcj.postgres.username}
    password: ${io.github.paulushcgcj.postgres.password}
    url: jdbc:postgresql://${io.github.paulushcgcj.postgres.host}/${io.github.paulushcgcj.postgres.database}
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  max-http-request-header-size: 2MB
io:
  github:
    paulushcgcj:
      postgres:
        database: ${POSTGRESQL_DATABASE:smash}
        host: ${POSTGRESQL_HOST:localhost}:5432
        username: ${POSTGRESQL_USER:user}
        password: ${POSTGRESQL_PASSWORD:passwd}
