name: Java Tests

on:
  workflow_call:
    inputs:
      environment:
        description: GitHub environment; usually PR number, test or prod
        default: ''
        required: false
        type: string

jobs:
  builds:
    runs-on: ubuntu-latest
    name: Test ${{ matrix.app.name }}

    strategy:
      fail-fast: false
      matrix:
        app: 
          - { name: "Spring boot reactive", path: "springreactive" }
          - { name: "Quarkus reactive", path: "quarkus" }
    defaults:
      run:
        working-directory: ${{ matrix.app.path }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ matrix.app.path }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ matrix.app.path }}-
    
    - name: Build with Maven
      run: mvn -B verify -P all-tests --file pom.xml

  results:
    name: Job Results
    if: always()
    needs: [builds]
    runs-on: ubuntu-latest
    steps:
      - name: Job results for (${{ inputs.environment}})
        run: |
          # View results
          echo "needs.*.result: ${{ toJson(needs.*.result) }}"

      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: |
          # Job failure found
          echo "At least one job has failed"
          exit 1