name: Pull Request Open

on:
  pull_request:

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  builds-fe:
    name: Build frontend (${{ github.event.number }})
    secrets: inherit
    uses: ./.github/workflows/.nodejs-build.yml
    with:
      environment: ${{ github.event.number }}

  builds-be:
    name: Build backend (${{ github.event.number }})
    secrets: inherit
    uses: ./.github/workflows/.java-build.yml
    with:
      environment: ${{ github.event.number }}

  results:
    name: PR Results
    needs: [builds-fe, builds-be]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
