name: Run Tests

on:
  workflow_run:
    workflows: ["Pull Request Open"]
    types: [completed]

concurrency:
  group: uat-${{ github.event.workflow_run.pull_requests[0].number }}
  cancel-in-progress: true

jobs:
  test-fe:
    name: Test (${{ github.event.workflow_run.pull_requests[0].number }})
    secrets: inherit
    uses: ./.github/workflows/.nodejs-test.yml
    with:
      environment: ${{ github.event.workflow_run.pull_requests[0].number }}

  results:
    name: PR Results
    needs: [test-fe]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"